etherlink:
  name: etherlink
  chainId: 128123
  domainId: 128123
  protocol: ethereum
  rpcUrls:
    - http: https://node.ghostnet.etherlink.com
sepolia:
  name: sepolia
  chainId: 11155111
  domainId: 11155111
  protocol: ethereum
  rpcUrls:
    - http: "https://sepolia.drpc.org"
presto:
  name: presto
  chainId: 686669576
  domainId: 686669576
  protocol: ethereum
  rpcUrls:
    - http: https://sn2-stavanger-rpc.eu-north-2.gateway.fm

